### ISSUE TITLE
Wither Minigame and Skyblock Arena

### ISSUE THREAD

**Issue by Pugabyte** [Pugabyte/BearNation#1]
We added the Wither Arena back in November of 2016, but it has barely been used since. I think it would be worth it to add it as a Minigame.

Also, since the addition of skyblock, we will need a Skyblock only wither arena so players can complete the wither star challenge.

**Comment by BearNationSMP** [comment]
**Pugabyte**: The senior staff discussed; we are changing the Survival Wither system to only fine you the $50,000 if you beat the wither AND get win a nether star.

Here's example situations (the exact details of example #2 are not thought out yet):
Starts match -> loses -> gets nothing, pays nothing
Starts match -> wins -> Gets elytra, pays $2,000
Starts match -> wins -> Gets nether star, pays $50,000 (if you dont have it, it will default back to example #2)

Additionally, we decided that all rewards are optional. You will be prompted to accept or deny the randomly chosen reward. 
If you do not have enough money to recieve the randomly chosen reward at the time, you will not get any reward.

**Comment by BearNationSMP** [comment]
**Pugabyte**: The senior staff discussed; we are changing the Survival Wither system to only fine you the $50,000 if you beat the wither AND get win a nether star.

Here's example situations (the exact details of example #2 are not thought out yet):
Starts match -> loses -> gets nothing, pays nothing
Starts match -> wins -> Gets elytra, pays $2,000
Starts match -> wins -> Gets nether star, pays $50,000 

Additionally, we decided that all rewards are optional. You will be prompted to accept or deny the randomly chosen reward. 
If you do not have enough money to recieve the randomly chosen reward at the time, you will not get any reward.

**Comment by Pugabyte** [comment]
Survival wither reworked. Putting skyblock wither back on the backlog cause no one is there.

**Comment by Blast-MC** [comment]
Wither Minigame scrapped for regular wither arena, skyblock wither mentioned on #249
