### ISSUE TITLE
Jungle rumble has a problem with the score board

### ISSUE THREAD

**Issue by JustSteveThings** [Pugabyte/BearNation#102]
Okay so basically sukhy and noah both have a  0second times https://i.imgur.com/6xbXtIZ.png
I know for a fact if we delete the map and reset it up it'll remove these times but everyone else will lose there own. Is there away for you to remove there time @Pugabyte  if not is there a possibility you can reset the scoreboard for the entire game. 

Note: Noah put a note into the Dev's github but it could take a while before it's added if at all.
https://github.com/AddstarMC/Minigames/issues/150

**Comment by Noahkiq** [comment]
this isn't just limited to junglerumble btw... I know your timeclash maze
has some invalid times and maybe a few others? tho the others might've just
been test games.

**Comment by Pugabyte** [comment]
manually deleted
