### ISSUE TITLE
Natural degeneration on spleef

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#112]
Submitted by **Pugabyte**

**Comment by JustSteveThings** [comment]
Heavy spleef doesn't make degeneration possible

**Comment by Noahkiq** [comment]
obligatory "mgm plugin does everything!!"

...no, but really, the MGM plugin has some settings for degeneration. The two most fitting ones here would probably be Inward and Circle (iirc). These remove the outermost rectangles and circles of blocks, respectively, then make their way inwards. These seem span the entire vertical length of the degeneration area, by the way, so they should work fine even for multi-layered maps. Degeneration can be set to start after X seconds, and then remove layers every Y seconds.

This should work fine for all Spleef modes, except for Splegg. (Which is, unfortunately for this situation, probably the most played of the Spleef gamemodes.)
