### ISSUE TITLE
Rainbow beacon

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#115]
**Pugabyte**: It was previously considered as a donor item, but rejected due to a couple of different reasons. I think we should revisit it 
- Create safeguard against glass farming
- Max of 1
- Stop/start depending on proximity of players

**Comment by FilidDamhsoir** [comment]
Glass isnt worth what it used to be, if they do farm it its not gonna be a huge impact. Esp if the limit is one. We should just do it

**Comment by Pugabyte** [comment]
A safeguard won't be hard to write, literally like 3 lines of code

**Comment by FilidDamhsoir** [comment]
I missed the write a safeguard line. Oops
