### ISSUE TITLE
Vanish is always on by default for admins

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#117]
Submitted by **Filid**

**Comment by FilidDamhsoir** [comment]
I'll add to the weirdness, you may be aware of or may not. I dunno if it will help in tracking the issue down at all:
  every new *game* we entered I would still be unvinished- I could hit and take damage.  Some people *could* see me.  But others I would be forced to vanish and then unvanish (or if they did a F3 +a manually). And who could or could not see me changed *each* game.   In one game Pochip could see me, in the next he couldn't, but MaxAlex saw me just fine.  On enterning the lobby for KodaCove I asked who could see me (in the lobby itself).  Only about 1/3 of the players present in voice reported they could- and it was a mix of staff and non staff on both the "sure I see you" and the "what? where are you" tribes.  
I did not think to test until now if whether they spawned where they should/shouldn't be able to see me affected it, or if entering lobbies before/after me affected it.

**Comment by FilidDamhsoir** [comment]
Uh. Wakka still can't see me or TP to me

**Comment by FilidDamhsoir** [comment]
With some testing-  Once they can see me, they can see me *until* they log.  Once *they* relog, I disappear- even if I am unvanished at the time

**Comment by Pugabyte** [comment]
Hasnt been a thing for a while. Cause unkown
