### ISSUE TITLE
Creative world VPS menu title oddity

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#119]
In the creative world VPS menu, the PlayerHeads title is a little janky

![jvevlke-slgf0h4wuvjvyw](https://user-images.githubusercontent.com/9204295/36931463-a5c47eb6-1e7b-11e8-9117-3de283ed01b2.png)

**Comment by Pugabyte** [comment]
The `(Staff)` part was failing the check for `if lore contains "Price :"`; fixed
