### ISSUE TITLE
Add auto-crafting to autosort

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#124]
**Pugabyte**: Suggested by Coomsy

Using `/autosort craft` will cause items such as ingots to be crafted into their respective blocks on certain events (pickup, chest/furnace access, etc).

**Comment by Pugabyte** [comment]
AutoCraft has been added on pickup event. Future additions:
- [ ] Lapis autocrafting
- [ ] Ability to toggle off autocrafting for certain items
- [ ] More triggers

**Comment by Pugabyte** [comment]
Moved to https://github.com/Pugabyte/AutomaticInventory/issues/4
