### ISSUE TITLE
Update VNP

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#136]
**Pugabyte**: Will require updating all my custom stuff that uses vanish integration

**Comment by FilidDamhsoir** [comment]
Reddit- create a BN account

Add the login on staff CP

Staff members take turns editing the intial thread to add peroidic updates kinda the way this is happening right now, here

**Comment by WakkaFlocka239** [comment]
Adding to Steve's comment about npc look...
In spectator mode, NPC's don't look at you, this is true as well for being in vanish and spectator mode.
Possible to trick citizens to thinking vanished players are in spectate, even when not?

**Comment by Pugabyte** [comment]
https://github.com/CitizensDev/Citizens2/issues/1490

**Comment by WarriorTark** [comment]
Being unable to open active furnaces or other blocks that have "active" states while vanished

**Comment by WakkaFlocka239** [comment]
That one bug where mods cannot see any rank above them even if the person they can't see is unvanished, and only fixed when you go into vanish and back out again.

**Comment by Pugabyte** [comment]
Possibly fixed  `/pex group MGMMod add essentials.vanish.see`

**Comment by WakkaFlocka239** [comment]
Just found out that you can be hooked by a fishing rod in vanish. Preventable?

**Comment by GoddessOfNyx** [comment]
Snowballs hit a vanished player and break.

**Comment by RavenOnACloud** [comment]
Your dogs still follow you when you're in vanish, if they are not are sat down.

**Comment by RavenOnACloud** [comment]
Vanished players as still shown on the enjin website, it's shows the amount of players + the vanished players. Their head icons don't show up though.

**Comment by RavenOnACloud** [comment]
You can open chests you can't open when you're vanished, eg. at the chests at the warps

**Comment by WarriorTark** [comment]
Walking on redstone ore in vanish still activates it

**Comment by GoddessOfNyx** [comment]
if a vanished player is in front of a boat, they can stop the boat

**Comment by Pugabyte** [comment]
LWC's double door mechanism is still triggered when vanished, leaving the adjacent door open.

**Comment by WarriorTark** [comment]
Shulker boxes do not silent open while vanished

**Comment by RavenOnACloud** [comment]
You still can rotate items in item frames while vanished.

**Comment by RavenOnACloud** [comment]
Vanished players trigger skeleton traps

**Comment by Shannontc** [comment]
After using /vanish and then using fakequit, it shows that you are in vanish but some (or all) players can still see you. Haven't looked into this issue much and not sure if this happens every time when you use the commands in this order.

**Comment by Pugabyte** [comment]
We will be moving to PremiumVanish in 1.13 so this is no longer valid. If there are issues with that plugin they can be reported directly to the dev as they are still actively updating the plugin.
