### ISSUE TITLE
Bookshelf plugin

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#137]
**Pugabyte**: Suggested by @RavenOnACloud 
Possibly a donor feature. Similar to https://www.spigotmc.org/resources/13219/ (source?)

**Comment by Pugabyte** [comment]
After looking into this, I found that the original source for the only good and recent plugin (linked above) no longer exists. I decompiled it (with author's permission), but after looking through it, I don't feel comfortable putting it on our server with the incoming 1.13 update.

**Comment by Pugabyte** [comment]
https://gist.github.com/aikar/131b372f9f47c2e3834d
