### ISSUE TITLE
Advertising

### ISSUE THREAD

**Issue by Pugabyte** [Pugabyte/BearNation#15]
A lot of Bear Nation's advertising content is over 2 years old now. It desperately needs updating. This issue will be a megadump of information/ideas when I have time to sit down and compile the information.

- [ ] Twitter
- [ ] Reddit

**Comment by FilidDamhsoir** [comment]
Reddit- create a BN account

Add the login on staff CP

Staff members take turns editing the intial thread to add peroidic updates kinda the way this is happening right now, here
Edit:
Filid added a fucking note dudes

2nd Edit: Steve is now talking about minigames

**Comment by Pugabyte** [comment]
This has been set into motion, all further discussion goes in #staff-social-media
