### ISSUE TITLE
New chat plugin

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#158]
**Pugabyte**: Megathread for requirements for the new chat plugin

- [ ] Included Discord support
- [ ] chatter#getHistory - Get DM history, allow it to be displayed back to them at any point in time
- [ ] Regex censor from configuration file
- [ ] JSON Support
    - [ ] Timestamps
- [ ] ? Show default rank prefixes for staff members to new players (custom prefixes are confusing)

**Comment by Pugabyte** [comment]
Completed in java
