### ISSUE TITLE
Koda improvements

### ISSUE THREAD

**Issue by Pugabyte** [Pugabyte/BearNation#16]
Everyone loves talking to Koda. We should add some more responses/triggers to make him even more fun to talk to.

**Comment by BearNationSMP** [comment]
**PugaBear**: Things about food
Aussie bashing jokes

**Comment by BearNationSMP** [comment]
**_leroy**: something about glitter everywhere
someone says aussie aussie aussie i say oi oi oi 
someone says fish are friends i say not food

**Comment by BearNationSMP** [comment]
**Filid**: how big is a pugabyte

**Comment by Noahkiq** [comment]
![image](https://user-images.githubusercontent.com/13265322/31097202-83809ed6-a78c-11e7-83f4-675befd15354.png)

**Comment by Pugabyte** [comment]
http://paste.bear-nation.net/dawap
