### ISSUE TITLE
Village Murder skulls

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#161]
**Filid**: I noticed playing murder that there were skulls in the tunnel near Sukhy's home, including some stacked on each other, like peoplel had died togther.  While typing a message about it during the game I died down there.  Now my head is there too. Can confirm, not being cleaned- but only looks likes its in the tunnel, may just be the region needs to be exanded down

**Comment by Pugabyte** [comment]
Added a check to delete all skull armour stands that are below y=0
