### ISSUE TITLE
Achievement plugin

### ISSUE THREAD

**Issue by Pugabyte** [Pugabyte/BearNation#17]
@JustSteveThings once suggested a plugin called [Advanced Achievements](https://www.spigotmc.org/resources/advanced-achievements.6239/). The idea behind this plugin is to add more objectives that people can work towards, similar to mcMMO, which increases interest in the game.

For example, there can be an "Achievement" for breaking 10,000 blocks of stone. We can have rewards, but I'd prefer that they were minimal. We should emphasize the achievements themselves, not the rewards. 

- [x] Ideas for achievements
- [ ] Ideas for rewards
- [x] Research new 1.12 Advancements system, see if it may be a more extensible solution (@Noahkiq? You're my expert Minecrafter. How do advancements work? Could they offer us more options for "Achievements"?)
- [x] Program/configure whichever system we decide to go with

**Comment by Noahkiq** [comment]
Custom advancements can be setup (check out [this guide](http://www.minecraftforum.net/forums/minecraft-discussion/redstone-discussion-and/commands-command-blocks-and/2809368-1-12-custom-advancements-aka-achievements) to learn how) which allow for running custom commands when someone gets an advancement. To go with this, a new `@s` selector was added which is set to the person who ran the command, or in this case, got the advancement.

**Comment by PugaBear** [comment]
@Noahkiq I read through a lot of it, but I'm not sure it can do the things I want. Can it, for example, count how many stone blocks the player has broken? How many endermites they have killed?

**Comment by PugaBear** [comment]
[This](https://www.reddit.com/user/Dinnerbone/comments/6l6e3d/a_completely_incomplete_super_early_preview_of/) is relevant if we go down the Advancements path so I'll keep it here

**Comment by Noahkiq** [comment]
Neither of those seem to be possible, but IIRC could be done with command blocks in a loaded chunk (which would be at the world's default spawnpoint) and scoreboards.

**Comment by PugaBear** [comment]
Then I'll just go with Advanced Achievements. Thank you

**Comment by JustSteveThings** [comment]
My thought and input (wrote when the idea 1st came up)
https://docs.google.com/document/d/17sgHpFIp7p0Bn6RpTluDzcdzqojkrv2DKPcxwWgGtxM/edit#

**Comment by Pugabyte** [comment]
All available achievements can be found on [the plugin's github repo](https://github.com/PyvesB/AdvancedAchievements/blob/master/src/main/resources/config.yml#L227)

**Comment by FilidDamhsoir** [comment]
JEnny and I are now working on this. Im putting thoughts/questions here since I'm sure you've got some thought on how you want to do it:

Acheivments- will they be viewable to only you, or can other people see yours too?
Will they be viewable in game, or via the website (hey a possible api use) or both?

**Comment by Pugabyte** [comment]
I was thinking ingame GUI and website, yes

**Comment by Pugabyte** [comment]
Plugin is operational, a separate thread will contain ideas for improvements
