### ISSUE TITLE
Mason can't tab complete names

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#174]
Submitted by **TheEpicScrub**

**Comment by BearNationSMP** [comment]
**TheEpicScrub**: I can't use tab auto compelte on names that follow commands like /warn /kick /ban or /msg but /tpa works

**Comment by Pugabyte** [comment]
Cannot reproduce (and therefore cannot find a fix). If you can find the condition that breaks it (such as being in vanish), I can fix it.

**Comment by Pugabyte** [comment]
@TheEpicScrub is this still an issue?

**Comment by Pugabyte** [comment]
Was essentials' fault. Spigot only allows tab completion on commands if the player has permission for that command. While LiteBans overrides the commands, it does not appear to override the tab completion. The solution was to give moderators all the permissions related to essentials punishments.
