### ISSUE TITLE
rideable bug?

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#175]
Submitted by **Filid**

**Comment by FilidDamhsoir** [comment]
Okay, So OG_Nesquick reported in chat he was stuck on a llama.
Teleporting to him did not teleport to him, but rather an empty spot like he'd died
teleporting to his friends, I found him on llama back, claiming that shift would not allow him to dismount, no error message (the reported being unable to see him)
using /s did not move or pull him, but kicking him did work to remove him. He spawned in a little way away from where I saw him when I did /kick though.  (like 5-10 blocks) in the spot where he was when he did shift to show me he couldn't dismount
Now you can't get on the llama.  And I can't open it to remove its carpet- like it doesn't exist

Bella also claims similar happened to her yesterday with a horse- she used /spawn to finally fix it and dismount

IDK whats going, but I'm documenting here for now hoping smarter pugs than me will know

**Comment by BearNationSMP** [comment]
**Filid**: I do howveer notice they are stupidly near the region to a warp, so that may have something to do with it?

**Comment by Pugabyte** [comment]
The interact flag appears to fix it, I've added it to all the warp regions
