### ISSUE TITLE
Global minigame quit command

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#178]
**Pugabyte**: Instead of different commands for each plugin we have (e.g. /mgm quit, /spleef leave, /ma leave, /hns leave), one command that automatically runs the correct command based on what you are currently playing.

**Comment by WakkaFlocka239** [comment]
Just Notes:
Spleef maps are split into 3 categories:
- spleef_
- splegg_
- bowspleef_
Mob Arena will be:
- mobarena_
And HideAndSeek will be:
- hns_
