### ISSUE TITLE
New minigames

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#184]
**Pugabyte**: 
- [x] Pizza 
- [x] Thom's Murder
    - [x] Needs name
    - [x] Needs lobby
- [x] Thunder's Starfox themed dogfighting map
    - [ ] Kinda wanna change name of gamemode
- [x] HideAndSeek
    - [ ] Adjust countdown and warn people about choosing a disguise
- [x] Randomize dogfighting spawn points
- ~~[ ] Implement an item to give to seekers on Hide and Seek to give them speed~~

**Comment by WakkaFlocka239** [comment]
Rename Dog Fighting to Aerial Assault? (Warrior_Tark)
