### ISSUE TITLE
Particle Effects

### ISSUE THREAD

**Issue by Pugabyte** [Pugabyte/BearNation#19]
Use either [CPE](https://www.spigotmc.org/resources/customparticleeffects.2725/), [UltraCosmetics](https://www.spigotmc.org/resources/ultra-cosmetics-opensource-and-free-1-8-1-12.10905/), or some other plugin to add super awesome particle effects that follow people around.

**Comment by BearNationSMP** [comment]
**Pugabyte**: Sell `/particlehats:h` as halos, capes and trails?

**Comment by Blast-MC** [comment]
written in java in bncore
