### ISSUE TITLE
Homes menu bugs/improvements

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#197]
**Pugabyte**: 
- [ ] The sign menu is invisible for some people, I need to change it to remove the sign after the menu is closed. 
- [ ] Make a more robust gui action handler

**Comment by WakkaFlocka239** [comment]
Pages! I want to be able to edit more than my first 27 homes.

**Comment by FilidDamhsoir** [comment]
THANK YOU ^^^
THAT. Now there are two pug.
