### ISSUE TITLE
Mute menu

### ISSUE THREAD

**Issue by Pugabyte** [Pugabyte/BearNation#2]
Bear Nation's chat can move very fast sometimes. I'd like to give users the ability to slow it down by adding a menu that controls their ability to see some of the optional messages, such as:

- [ ] Custom Trade Sign alerts
- [ ] AFK Messages 
    - Turned off by default, will post a message in chat when someone goes afk
    - Includes the AFK message system (`/afk <message>`)
- [ ] Global/IRC/Koda/Discord 
    - Group these together?
- [ ] Local
- [ ] Minigames/Creative/Skyblock
    - Will only display one (or none at all) depending on your current world
- [ ] Automatic broadcasts 
    - Only for a certain rank and above? 
    - Integration with #50?
- [ ] Dubtrack announcements

----
Steps I need to take to complete this task:
- [ ] Design the menu
- [ ] Research/test best way to hide permission based things
- [ ] Decide which ones will be persistent (kept on logout) and which ones will not 
- [ ] Edit some of the existing code (AFK, Dubtrack, etc) to allow me to control whether each player can see it
- [ ] Program it

**Comment by Pugabyte** [comment]
![](https://i.imgur.com/ZhDEIX7.png)

**Comment by BearNationSMP** [comment]
**Pugabyte**: Minigame messages
