### ISSUE TITLE
add a modifer to forcechannel

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#211]
Submitted by **Filid**

**Comment by FilidDamhsoir** [comment]
One that can maybe that disabled the "no one is around to hear you" thing for that session, or an hour so something, so that we can move problem kids to local and it wn;t immeditly tell them how to get back out while we deal with them

**Comment by Pugabyte** [comment]
I'd prefer a staff member unvanishes while speaking with a player in local chat. It lets the player know there really is a person talking to them, not just some bot or whatever.
