### ISSUE TITLE
NPC Staff Change

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#224]
**Arbiter6784**: Multiple NPC's require updating in the Staff Hall. Wakka, Raven and Lachlan require rank updates to Admin, Operator & Builder respectively and my NPC needs an update to allow for the clicking description to work.

**Comment by WakkaFlocka239** [comment]
Also, the NPC's at spawn need updating, are the new mods there yet? And idk about the other ones but when you right click me, it says im an operator or something.
