### ISSUE TITLE
Showcase page update

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#236]
**Pugabyte**: Someone please help compile a list of all the builds that can be added to http://bnn.gg/showcase. Additionally, if you have good shaders, feel free to take screenshots and share them (via imgur to avoid quality loss) on this ticket.

- [x] Pugmas Villages
- [x] Bear Fair
- [x] Herobrine's mansion
- [x] Forgotten Gulch
- [x] Midtown
- [x] Ellwood Keep
- [x] StarFox
- [x] Sodai Temple
- [x] Capshire Keep
- [x] Longreach
- [x] Paris
- [x] FSS Centaur
- [x] Lazoria

**Comment by FilidDamhsoir** [comment]
Ellwood Keep is steves

Starfox or one of the space maps in progress
Sodai Temple maybe? 
Pure claritys(?) Castle
