### ISSUE TITLE
koda donation announcement

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#246]
Koda should broadcast each donation received by the server, could include...
- What they bought (package/custom amount)
- Amount
- A thank you
- etc.

**Comment by Pugabyte** [comment]
Should it have its own discord channel? Only be announced in-game? Go to #general? 
Someone please draft up the exact template for the messages. There can be multiple for different tiers.

**Comment by FilidDamhsoir** [comment]
in game, in bridge. I don't think it needs a channel too.  
Honestly, one short, simple message seems best
Like how koda congrats new members

just "Thank you for your Donation, %Player% !"  Maybe add an "Enjoy your new %Perk% from our store"  with a link to get others to go to the store?

**Comment by WakkaFlocka239** [comment]
Oh we also talked about javing it show up in general aswell.
