### ISSUE TITLE
jiggles cant place anything in his own plot on creative.

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#248]
**Filid**: Ask wakka for details, im just making the issue at his request and I wasn't really listening while he was trying to figure it out.

**Comment by FilidDamhsoir** [comment]
Okay, I was paying some attention:

Relogging didn't fix it.
They would place, it would immeditly rebreak/disapper,  but they could break.

Even josh in his own plot.

We had been trying to disgusie them right before hand (so we didn't have the same players in every video) but even undis and relog didn't fix the issue
