### ISSUE TITLE
setup permissions/access to PocketGames

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#253]
should people get access to it via ingame ranks or server store, or both?

guest/members should have the permission to accept challenges from other players who have perms to the games. I believe they need all of these permissions for it to work:
    - pocketgames.commands
    - pocketgames.commands.menu
    - pocketgames.commands.help
    - pocketgames.commands.multiplayer
    - pocketgames.commands.menu
    - pocketgames.commands.duel

**Comment by Pugabyte** [comment]
Removed from server
