### ISSUE TITLE
check vote sites for proper description

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#261]
**Filid**: while the last advertising thing says that further advertsing goes in staff social media, this is more a check list thing as a reminder to look at this.  and not just for pug. Any moderator can do this

**Comment by jenthakkar** [comment]
03/13/2019 - updated each of the descriptions a little bit to keep it up to date (for example one of them said we are a new server with two owners lol)

i think its beneficial if whenever someone edits them we make a note so we know the last time we did it.
