### ISSUE TITLE
Website start server tool not working

### ISSUE THREAD

**Issue by Pugabyte** [Pugabyte/BearNation#263]
The first challenge was allowing the command to run without a TTY; edited visudo and created a shell script to solve that. This error then showed up:

``
error: mark2 is unconfigured! run `mark2 config` or `mkdir /etc/mark2 && touch /etc/mark2/mark2.properties` as root
``

I've created mark2 configs in `/home/{griffin,minecraft}/.config/mark2/mark2.properties`, `/root/.config/mark2/mark2.properties`, and `/etc/mark2/mark2.properties` but the error persists. 

@jenthakkar You're more familiar with python than me. Any idea why it might not be finding the `mark2.properties` file? This is the shell script:
```sh
cd /home/minecraft/servers/$1 # change working directory to specified server's root folder
sudo -u minecraft /home/minecraft/mark2/mark2 start # start server with minecraft user
```

It works fine when run without a shell script.

Resources:
[Error origin](https://github.com/gsand/mark2/blob/master/mk2/launcher.py#L336)
[find_config method](https://github.com/gsand/mark2/blob/master/mk2/shared.py#L22-L38)

**Comment by jenthakkar** [comment]
can i have the shell script?

**Comment by Pugabyte** [comment]
After taking another look at this I solved it with screen sessions; 

```
exec("/usr/bin/screen -S mark2 -X stuff 'cd /home/minecraft/servers/smp ; echo -ne \015'");
exec("/usr/bin/screen -S mark2 -X stuff 'mark2 start ; echo -ne \015'");
```

If you have time and would like to fix mark2, I'd appreciate it and would rather use that, but this is a workaround until then/if you are too busy. :)
