### ISSUE TITLE
World editing in 1.13

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#264]
**Pandanakinz**: I know FAWE in 1.13 is broken anyways, but I can barely use voxel for more than a few minutes right now without the server crashing and I’ve no idea why. Any way to fix that without just waiting for better w/e?

**Comment by Pugabyte** [comment]
https://github.com/boy0001/FastAsyncWorldedit/issues/1144

**Comment by Pugabyte** [comment]
Appears to be resolved
