### ISSUE TITLE
Homes update

### ISSUE THREAD

**Issue by Pugabyte** [Pugabyte/BearNation#27]
Homes was one of the first large plugins I made. It is a complete and total _mess_ and desperately needs some attention.

- [x] Refactor and cleanup
    - [x] Reusable methods for common processes
    - [x] Use updated methods that I had no idea existed when I first made this
- [ ] Paginate menu
    - If a player has more than 36(?) homes, not all of the homes will appear on the menu. I think only Filid has reached this point but it's still something I should address.
- [x] Either hook directly into essentials to get homes list or remove essentials dependency completely and handle everything myself
    - I'm currently using command listeners... which is a horrible idea. If the command fails due to a permission error or some random exception, my database won't reflect that.
- [ ] /homes \<player\> should only show homes the player can access
- [x] Color code /homes [list] with locking (white if unlocked)
- [x] Make it more user friendly
    - [x] Try to display more information in hovers
    - [x] Overall make it easier to view information
    - [x] Ability to set a home to a custom item
         - If there is a custom item, and the home is locked, enchant the item

Open to suggestions

**Comment by BearNationSMP** [comment]
**PugaBear**: Option to prevent players from setting a home in a pstone

**Comment by Pugabyte** [comment]
In progress

**Comment by Pugabyte** [comment]
Done with most of this. Closing for now, will revisit in the future when another update is due.
