### ISSUE TITLE
Tark breaks boxes

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#285]
**Filid**: When Tark opens a chest or shulker box, it remains in the open position still  (he says he showed pug this months ago).  its possibly to get stuck on them like ghost blocks in mcmmo, but fixghostblocks does not fix it.  unloading the chunk removes it.  Leaving the chunk but returning to it while tark remains in the area makes it appear fixed for the person who left- which means that tark appears to be flying by standing on the open shulker lid.  screenshots to follow shortly

**Comment by FilidDamhsoir** [comment]
In additon- if tark has opened it and it is stuck- my attempting to open a box that appears closed to me will cause one of three things to happen-
the open animation won't play, it will function as normal, OR it will open and be stuck for me too.  It seems random which one happens- but consistent ? opening the same one over and over will yeild the same result every time, even if I teleport away and back to visually clear them on my screen

**Comment by WakkaFlocka239** [comment]
does this still occur?

**Comment by Pugabyte** [comment]
@FilidDamhsoir

**Comment by Pugabyte** [comment]
Havent heard back, closing
