### ISSUE TITLE
Teleporting NPC's To Different Worlds "Breaks" Players

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#291]
<img src=https://i.imgur.com/IjoG426.png>
<img src=https://i.gyazo.com/6a2ccef324efd51e8075a1f0b59c9efd.png>

**Comment by Pugabyte** [comment]
Prevented by https://github.com/Pugabyte/Nexus/commit/5165bd48dbced1caf67be266a6f87a6472d9aadb
