### ISSUE TITLE
wings throws an error when users go to the gl from the bfe

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#305]
**Filid**:  https://gyazo.com/35e3ee67af67364f0d123d745f23174c  I noticed this the other day after wakka drug me to the BFE, and again today with John.  I have not yet figured out what the order of events is that triggers this- if theres a specific wing, if you have to log out then back in.  I just know that under some set of conditions this error will start spaming console, that the player causing it always seems to be in the gl when it happens, and that running the wings menu toggling the wings on and then back off makes it stop

**Comment by Pugabyte** [comment]
Moved to Java
