### ISSUE TITLE
Toggle /gamemode 3 off and /fly on when using /rh

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#307]
**Porkeroni**: unless there's a particular reason why you are made to stay in spectator mode when using /rh, it would be helpful if it got turned back to /gm s and /fly got toggled on. I was following a player around today in spectator mode trying to catch him x-raying, he then started to fly around the map and after using /rh i had to go back to survival cause he couldn't see me, and also toggle /fly just to get to him cause he was 50 blocks in the air so this would be helpful for similar situations

**Comment by Pugabyte** [comment]
@Porkeroni I've made the changes, please test and close the issue if successful
