### ISSUE TITLE
/prefix &r

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#308]
**Blast**: &r does not work with /prefix. https://i.imgur.com/xu66ynp.png

**Comment by WakkaFlocka239** [comment]
&l, &k, &n, &m, and &o are all not allowed in prefixes, and since &r, is technically a format, this now occurs.
<img src=https://i.imgur.com/Tm0F324.png>

**Comment by Pugabyte** [comment]
changed to replace &r with &f
