### ISSUE TITLE
Make a command along the lines of /nycb that is for telling players about land claiming/grief protection

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#311]
**Arby**: Possibly something along the lines of: As we have a strict no griefing policy here, whatever you build on is essentially yours! 90% of grief is caught by our staff before it even happens and any grief that may happen to you will be rolled back. We do offer pstones though which prevent players from doing anything in a certain region.

**Comment by noellekiq** [comment]
and/or koda auto trigger ("claim land", "grief protection", something like that)
