### ISSUE TITLE
Rename WG Regions

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#313]
# NOTICE: NOT OFFICIAL WORLDGUARD REPO
## We are just a server that uses WorldGuard, and this ticket is to write custom code to rename regions

A command that would allow us to rename regions on the fly, instead of having to...
1. Open wg/worlds/\<world\>/regions.yml
2. Finding the region in the massive list from the file
3. Renaming the region
4. Saving the file
5. Closing the file
6. Reloading WorldGuard, and realizing I spelled it wrong

**Comment by DeleteMetaInf** [comment]
I would really like a /rg rename command as well! I was surprised that such an obvious feature wasn’t already in the plugin.

**Comment by Pugabyte** [comment]
Hi @DeleteMetaInf! Just to make sure you are aware, this repository is just for the server that this team runs, not for WorldGuard. If, when we get around to this ticket, we find a way to do this, I'll reference the code change in this ticket. However it will be inside our custom plugin, so you will have to copy that code manually into a plugin if yours.

**Comment by DeleteMetaInf** [comment]
Oh, whoops. I thought this was the WorldGuard repository. My apologies.

**Comment by stryker2k2** [comment]
@WakkaFlocka239 - you rock!

**Comment by GriffinCodes** [comment]
@stryker2k2 In case you didn't notice the giant text at the top of the issue, we are not WorldGuard. The official issue is linked above with an explanation as to why it is not a feature yet. We added a custom implementation that worked for us, but is not perfect.
