### ISSUE TITLE
censor deUnicode errors

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#314]
<img src=https://i.imgur.com/cha57z6.png>

/facepalm, seems to be the only emote triggering the error
<img src=https://i.imgur.com/qvXsqdh.png>

**Comment by Pugabyte** [comment]
Was removing the leading zero 
![image](https://user-images.githubusercontent.com/12417961/70875512-3a270000-1f84-11ea-948e-d9f47c8cd0db.png)
