### ISSUE TITLE
autosort's autocraft eats blocks when inv full

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#322]
**Filid**:  I was trying to sort out all my dumpchests, I turned on autosort for the inventory in order to make blocks of coal/redstone/diamond ect.  
When i tossed my diamonds down, I only had 1 free sport in my inventory. It picked up the loose diamonds, but the blocks it made just disappeared.  Prism says I picked them up, and freeing up space in my inventory in the same spot doesn't make them reappear- but it means that autocrafting when your inventory is full will lose the full blocks

**Comment by FilidDamhsoir** [comment]
https://gyazo.com/7abe2361c4b3a30c7b36fb14cc43c50a
https://gyazo.com/a13ed5d52a0460004d304b86ef7d1068
