### ISSUE TITLE
JustEly cant /pet ride her horse- SimplePets

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#323]
**Filid**: She has the perms. The perms are the same as other players with the same perk.  I had to make a command sign that ran /^pets ride for her to be able to mount.  If it had worked with /pets ride, I would assume its the stupid mac keyboard issue, but other than command sign's run as Op or me sudoing her, it wouldn't work, and there was no error message.

**Comment by Pugabyte** [comment]
A simple google search shows a different permission
