### ISSUE TITLE
/leash bugs

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#324]
In the image below, i clearly typed the wrong command, but when i tried it. It lagged the server when the a player cannot be found. 

<img src=https://i.imgur.com/9HUOIZ6.png>

 I also accidently /leash tehpig twice, and i was able to unleash from one instance, but not the other.

<img src=https://i.imgur.com/IHqhHkK.png>

Also, I left the server to hopefully fix it, and it was spamming console.

<img src=https://i.imgur.com/nkKWOI4.png>

Along with all of that, as you can see, the error messages are a bit weird.

**Comment by Pugabyte** [comment]
Server lag and null prefix in error messages fixed
