### ISSUE TITLE
Spawn eggs messed up in creative world

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#328]
**RavenOnACloud**: Spawn eggs aren't working. Lindyy10 can't use spawn eggs from her inventory, nor middle clicking on mobs give her working spawn eggs. She however, can use spawn eggs I gave her. Spawn eggs she get look like this: <img src=https://cdn.discordapp.com/attachments/133947136382468096/627756573099556874/unknown.png

**Comment by BearNationSMP** [comment]
**Filid**: The first time I saw it fail, I assumed it was an intentional change I'd forgotten about, with all the guest trolls we've had.  But I just checked the permission nodes and the config. 
-Spawn egg true is still set.  Mob cap of 10.  

-Permissions are the same for everyone until moderator.  Moderators get the added admin and flag set permissions. 

-World guard doesn't *appear* to be blocking anything

So then I did some digging.  *No one* below moderator can get a spawn egg from the creative menu into their inventory- the moment it hits their hotbar it greys out and becomes unusable.  
However, if a staff member gives a player a working egg by dropping it to them- it works fine up to the mob cap.
 
Google search has one old issue similar to ours with an answer from the plot squared dev that suggests that world guard should not (or maybe does not need to be) used with plot squared- its hard to tell because his english is so bad.

So I'm thinking its likely world guard issue, even though world guard's flags in this world have nothing to do with mobs, and the only WG region is the global one that is set up for vine growth/leaf deacay/ect.

**Comment by WakkaFlocka239** [comment]
As a workaround, I've made a command to replace the empty mob egg with the type that you want:
`/spawnegg <mob name>`

**Comment by Pugabyte** [comment]
Please verify if still an issue

**Comment by WakkaFlocka239** [comment]
mob spawn eggs can be used in creative, tested it with a guest
