### ISSUE TITLE
Murder messages are giving away who the murderer is

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#331]
Village, SandySuburb, RavensNestEsate, and Necronomicon
all give away who the murderer is, and some have spelling errors in the messages.

**Comment by WakkaFlocka239** [comment]
Scranton is the only one that works properly

**Comment by noellekiq** [comment]
fixed. solution is just to leave this blank (in team options)
![image](https://user-images.githubusercontent.com/13265322/67126604-7842b600-f1c5-11e9-8c30-cd9086334202.png)
