### ISSUE TITLE
Fix Killer Money perk in VPS part 3

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#333]
**Filid**: Reported to me by Boffo.
I know some of this was a known issue, but since the only issue I found about it was closed, I decided to document what was going on here, just in case any of this wasn't already known.  and so that if someone else does get a report, they can see its already an known issue

 When selected, killer money closes the vps window.  It gives no output. It does not enable the perk, and it does not take the players vote points. <-- Pretty sure we have seen this before
This is the error that appears in console.
https://gyazo.com/6e27140eb51d6eb411c6d5de9989ecb8

So I checked the skript:
``` command: "console: kmboost [player]" ```

if you run that command manually through console-  kmboost with a player name? exact  same error. I found the skript for it, then I remembered I don't skript- just because it looked consistant with other skripts to me didn't mean it was working. 

Now, if boffo had wanted me to,  I could have manually added the pex command.  Only when I tested that- it didn't actually provide a boost.  And I know that's been an issue before, I just don't remember how we fixed it.  But a google search says the pex  perm is correct- but I don't see the vps category in KM's config.  Has the config gotten messed up (like ina  plugin update), or were we defining the boost for that someplace other than directly in KM's config?

**Comment by Pugabyte** [comment]
Not sure why but [the config was changed 5 months ago](https://github.com/Pugabyte/Server/commit/2196c2716bbbed2bff98ce3d29c03eb0b3ab3829#diff-5ffcaf3bb96cfb5aec6f5ff7f8a06d6e)

This should fix it:
![image](https://user-images.githubusercontent.com/12417961/69257061-69666f00-0b88-11ea-8db7-5f3d71f01efb.png)
