### ISSUE TITLE
BNCore Errors

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#340]
Don't close this ticket.

Fixed:
- [ ] timeafk
- [x] tickets tp
- [x] tickets close
- [ ] ...

Internal error, Ran `timeafk <player>` from console:
<img src=https://i.imgur.com/Vv0wW57.png>

NPE, when teleporting to a ticket (was teleported):
<img src=https://i.imgur.com/tL9SkT3.png>
<img src=https://i.imgur.com/Yx3skA5.png>

Null, When closing a ticket (ticket did close):
<img src=https://i.imgur.com/n1Nz8cl.png>
<img src=https://i.imgur.com/vgtNb7n.png>

**Comment by Pugabyte** [comment]
Fixed ticket issues
