### ISSUE TITLE
(FFA) Victory By Score Broken

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#355]
victory by min/max/total score broken on FFA games (details/repro below)

**Comment by lexikiq** [comment]
currently completely broken, there is no way to win by score
![brokenscore](https://user-images.githubusercontent.com/13265322/74685236-e6ab7b00-519b-11ea-978e-3fec184d627e.gif)

**Comment by lexikiq** [comment]
overall score works now, will make separate issue for min/max
