### ISSUE TITLE
Multiple dailyrewards messages displayed while daily rewards menu open

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#357]
**Camaros**: The daily rewards message displayed multiple times while the menu was open to claim rewards. Unsure if streak was actually advanced 3 days, or the message was just displayed 3 times.

**Comment by Shannontc** [comment]
![image](https://user-images.githubusercontent.com/34956355/74629829-d1443b80-511e-11ea-86d7-667662bbd372.png)
