### ISSUE TITLE
Fire doesn't get put out when respawning

### ISSUE THREAD

**Issue by lexikiq** [Pugabyte/BearNation#364]

**Comment by lexikiq** [comment]
- go into fire/lava
- die
- respawn
- you are still on fire

note that if a respawn location is set, you'll be burning at the respawn location, but then the fire will be extinguished when you get teleported to your actual spawn location

**Comment by Pugabyte** [comment]
Have seen this work properly in the past couple days, I'm going to count it as a client side bug, maybe fixed post 1.12
