### ISSUE TITLE
Multiplayer mechanics don't apply all loadouts

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#370]
**Blast**: If there is more than one team, one of the teams does not get their loadout

**Comment by Blast-MC** [comment]
Appears to be a file error. Not sure how it happened, but 3 paintball arenas are saved with just an id (*id001) instead of inventories/effects. Can resolve with a temp fix.

**Comment by Pugabyte** [comment]
`*id001` is a reference to another YML section

![image](https://user-images.githubusercontent.com/12417961/76332631-fdd71780-62c6-11ea-8b96-974570fa04f0.png)
creates this ->
![image](https://user-images.githubusercontent.com/12417961/76332593-f44daf80-62c6-11ea-8cfd-e6e39929162f.png)

This is just a space saving optimization made by the YAML parser, and shouldn't affect anything.

**Comment by Blast-MC** [comment]
The issue seems to be resolved. A reload of BNCore fixed it. I'll watch out for this happening more in the future and look for a fix if it comes up.
