### ISSUE TITLE
Don't triple up logs

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#38]
**PugaBear**: When I added the staff bridge I carried over the functionality we had on IRC of broadcasting the mod commands (/freeze, /warn, /pr, etc) to the staff channel. That's already done on discord in staff-log, and ocassionally, in the right circumstance, in staff-alerts. Does anyone have any ideas on how to consolidate these logs without them losing their purpose? (Like having it broadcast in staff-bridge is good so we can see what's going and talk to people handling it right there, and staff-log is good for... logging.)

**Comment by Pugabyte** [comment]
Gonna just leave it as is for now.
