### ISSUE TITLE
 Guests able to place lava

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#380]
**Filid**:  AFAIK lava (and TNT?) are still supposed to be trusted and above, but ```@Arbiter6784 > oh is it members now ◔‿ ◔
raveennnn > Ty
TheSovietBanana > yup i could put my lava for my iron farm and im still member
@Arbiter6784 > wait what
CapiteinSam > i have lave and its memebers and up same with tnt```
CapiteinSam is a Guest

**Comment by Pugabyte** [comment]
Lava/fire/tnt placing is enabled for members, has been for a long time. Tested with guests, CNR

**Comment by WakkaFlocka239** [comment]
<img src=https://i.imgur.com/DXWecph.png>
In the code, the player must have access to "use.fire" to not trigger the prevention for lava, fire, tnt etc.



<img src=https://i.imgur.com/l6Dy0WC.png>
and the group guest does not have this permission

so I'm not sure what happened here.
