### ISSUE TITLE
thrown maps disappear?

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#387]
**Filid**:  twice in the last hour Ponyo has used Q  to tossed a fresh/new/unrevealed  treasure map to a staff member and its just poof'd out of existance without getting slurped into anyone's inventory.   
But I can toss one thats already partially filled in to her, and she can toss it back no issue

**Comment by Pugabyte** [comment]
https://github.com/Ruinscraft/Panilla/issues/43
