### ISSUE TITLE
Item frames no longer count as valid chair ending

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#388]
Submitted by **Pugabyte**

**Comment by WakkaFlocka239** [comment]
Seems that the code to do it was commented out / removed
https://github.com/Pugabyte/Chairs/blob/arrow/src/main/java/com/cnaude/chairs/core/SitUtils.java#L232

**Comment by Pugabyte** [comment]
Switched to GSit, chair endings no longer required. /sittoggle to disable sitting
