### ISSUE TITLE
Boats triggering resource world banned items message.

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#392]
**Camaros**: When getting out of a boat or standing (jumping) on a boat, it triggers the message that you can't bring certain blocks into the resource world.

**Comment by Shannontc** [comment]
![image](https://user-images.githubusercontent.com/34956355/81995781-e262f280-9610-11ea-9d40-c320dfe8adda.png)

**Comment by Shannontc** [comment]
Also happens when going through this door.
![image](https://user-images.githubusercontent.com/34956355/81995843-1211fa80-9611-11ea-8c89-991bf32a9fc5.png)
