### ISSUE TITLE
Did we convert skript particle/wings permissions to java permission?

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#410]

**Comment by Blast-MC** [comment]
Shapes: particle.shapes
Effects: particle.<enum name(), replace "_" with ""
Wing Effects: particle.wingstyle.<enum name()>

They have not been changed over in the permissions file as far as I know

**Comment by Blast-MC** [comment]
converted wings to wings.use and wings.style.# with #429. Will look check other permissions to see if they have been converted and will close when complete

**Comment by Blast-MC** [comment]
Pork's permissions are updated, and he confirmed he had all the particles he owned before. I don't know who all has particles, so I'll fix it when the time comes. :)
