### ISSUE TITLE
home bugs

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#411]
**Filid**:  if my home is set in an area with a low celling- 2 blocks high I take damage every time I teleport ``/home Filid test``  to experince this.  It seems specfic to the block above me being a full block- staircases don't do this - even if the solid part is at the top half of the block.
``/home Filid test2`` and ``/home Filid test3``
Seems to be because of the little hop you do on teleport.  Possibly also related every time I log off, my homes ``115ship`` and ``116`` both spawn me *outside/above* the locations they were.  Which means instead of teleporting inside my sunken ship or the nearby cave, I end up in the ocean above them.
I have tried deleteing and reseting those homes, thinking maybe I'd put a block in the way and so it was teleporting me up,  but to no avail- i end up under the water, at the bottom of the ocean.  Which seems like the opposite of what safetp should do- instead of putting me safely in my house, its putting me in danger

**Comment by Pugabyte** [comment]
Please confirm and close if fixed

**Comment by Pugabyte** [comment]
@FilidDamhsoir
