### ISSUE TITLE
Prevent spawning potions, tools, books, etc in Creative

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#419]
**Pugabyte**: Anything that can have meta and be annoying to deal with. Trusted bypass

**Comment by WakkaFlocka239** [comment]
All items that we have seen players in the past spawn for nefarious reasons
- [ ] books (written & writable)
- [ ] enchanted books
- [ ] knowledge book
- [ ] potions (norm, splash, lingering)
- [ ] tipped arrows
- [ ] spawn eggs
- [ ] tools (shovel, pick, axe, hoe, fishing rod, shears)
- [ ] weapons (sword, bow, crossbow, trident, shield)
- [ ] armor (helm, chestplate, leggings, boots)
- [ ] chest
- [ ] trapped chest
- [ ] barrel
- [ ] shulker
- [ ] command block (all 3)
- [ ] fireworks

Blocks that have inventories, and could also be used for nefarious reasons
- [ ] hopper
- [ ] dispenser
- [ ] dropper
- [ ] furnace
- [ ] smoker
- [ ] blast furnace
- [ ] chest minecart
- [ ] furnace minecart
- [ ] hopper minecart
