### ISSUE TITLE
Discord mentions and Alerts

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#42]
- [x] ~~Clean up and announce /discord mention <name>~~ Replaced with @<ign>
- [x] When someone says "@<player>" ingame, figure out if the player exists in the `/discord link` database, and replace that with a mention on bridge.
- [ ] Figure out how I want to do alerts on discord

**Comment by BearNationSMP** [comment]
**Pugabyte**: When someone says "@<player>" ingame, figure out if the player exists in the bridge database, and replace that with a mention on bridge.

**Comment by Pugabyte** [comment]
Will complete when #177 is done
