### ISSUE TITLE
Splegg map Eggstraterrestrial has unbreakable blocks.

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#422]
**Camaros**: Normal terracotta blocks (not colored) and wooden blocks are not able to be broken while playing splegg on that map.

**Comment by Pugabyte** [comment]
Most splegg maps are likely affected, go through each map and pickblock all unique blocks, then add them to the block list

**Comment by Blast-MC** [comment]
I’ve already set them up, I just missed those 2 blocks. Just need to be added
