### ISSUE TITLE
late join players don't autobalance?

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#426]
**lexikiq**: curret joined fightnight and it put her on white making it a 4v2 despite team balancing being 50/50

**Comment by Pugabyte** [comment]
Please test if https://github.com/Pugabyte/BNCore/commit/f35db82dc5b16692dcb4cd59fcbef24aa90d75d5 fixes this

**Comment by Blast-MC** [comment]
Team balanced multiple times, fixed
