### ISSUE TITLE
Bear Fair Store TODO

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#438]
- [x] Particle & Wings commands
- [ ] Buying paintings at the gallery --> choose which world to get them in for Delivery Service
    And a way to get to the gallery

**Comment by Blast-MC** [comment]
Added /wings preview <style> command as well as converted the signs at the bfe to the new system

**Comment by WakkaFlocka239** [comment]
Couldn't get buying paintings automatically using delivery service to work, made buying them manual, and will be releasing the store soon
