### ISSUE TITLE
Future build contest ideas

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#45]
**PugaBear**: 
- Greek
- Village
- Castle
- World cultures 
- Micro/mini

**Comment by BearNationSMP** [comment]
**PugaBear**: Also consider adventure map contest

**Comment by BearNationSMP** [comment]
**Locklan**: Oriental (medieval japan/china), Underwater, Fantasy (eg Elven, Orc), Arena, New Biome (my fav, if i ever hosted one dis would be it lol), Sky (eg dragons, aeroplanes, floating castle, balloons etc), Theme a contest on a certain type of blocks (eg all blocks from 1.12 update or all blocks found in the desert), Biome theme, Animal (eg actual animal, or make up an animal with a story), Transport, Monument (eg giant pug headed statue lmao), Aztec, Egyptian, Ruined theme, City.

**Comment by BearNationSMP** [comment]
**_noahkiq**: example

**Comment by BearNationSMP** [comment]
**_leroy**: elven style (similar to dwarven style but elven)

**Comment by BearNationSMP** [comment]
**Sukhy**: Modern, victorian era

**Comment by Pugabyte** [comment]
Next build contest will be World Cultures

**Comment by jenthakkar** [comment]
Video Games
Elemental (Water, Fire)

**Comment by PandaVaderkinz** [comment]
Ancient Civilizations (Kind of a combination of Greek, what people made for “world cultures”, and other of those types.

**Comment by arbiter6784** [comment]
- Western

**Comment by ValillaTea** [comment]
- Seasons (Autumn, Winter etc.)
- Nautical (Ocean, Sea, underwater) 
- Block pallet (Giving a limited option of 9 blocks - very rough idea, would it really work? not sure...)
- Colours (Theme of e.g. Yellow, or BN colours (Yellow & Blue))
- Lab
- Nature/Biome 
-  My favourite thing... (... in minecraft, ...on Bear Nation)
- Style of build (Modern, Medieval etc.)

**Comment by PandaVaderkinz** [comment]
Build Competition in duos/teams
