### ISSUE TITLE
Autocraft broken/missing

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#450]
**lexikiq**: `/autosort autocraft` throws a generic error line implying input was invalid and doesn't seem to do anything
if it's not implemented yet then it should probably be removed from the store page/usage line :p
![image](https://user-images.githubusercontent.com/13265322/88431386-38e66d00-cdc8-11ea-8d44-d18e9d0d096c.png)

**Comment by WakkaFlocka239** [comment]
<img src=https://i.imgur.com/rgThjeZ.jpeg>

**Comment by Blast-MC** [comment]
We do have /compact, but it is in BNCore and not part of the automaticinventory plugin
