### ISSUE TITLE
Blacklisted items can still be transferred to the resource world.

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#452]
- [ ]  Blacklisted items only checks the players current inventory, and not their survival inventory. If you go to minigames/creative first, you can then go to /warp resource and bypass the item restrictions.

**Comment by PonyoBear** [comment]
Blacklisted items can be transferred through putting them in /autotrash and taking them out after going to /warp resource.

**Comment by Blast-MC** [comment]
Resource world must now be entered through survival world group, not minigame world, creative, etc. Autotrash will require a rewrite to fix. Will reference #437 and close
