### ISSUE TITLE
joining paintball causes tons of errors

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#462]

**Comment by WakkaFlocka239** [comment]
and times out all players, but doesn't crash

**Comment by Blast-MC** [comment]
World edit pasting has somehow fucked itself again

**Comment by WakkaFlocka239** [comment]
I updated FAWE, clearly was a mistake

**Comment by WakkaFlocka239** [comment]
This should be fixed by now
