### ISSUE TITLE
McMMO Scoreboard Internal Error

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#464]
Submitted by **Amixalot**

**Comment by Blast-MC** [comment]
When /scoreboard is on your screen, /mctop and /mcstats sometimes creates the error, "an internal error has occured when attempting to perform this command" in red font. When this happens, even if you turn /scoreboard off, /mctop and /mcstats wont work for the session

**Comment by Blast-MC** [comment]
Duplicate to #385
