### ISSUE TITLE
Thimble: players can remove the blocks from their head

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#497]
and they are unable to put it back

**Comment by WakkaFlocka239** [comment]
Also, the game doesn't want to start automatically

**Comment by lexikiq** [comment]
took a look at it and i'm not sure why [this listener](https://github.com/Pugabyte/Nexus/blob/master/src/main/java/me/pugabyte/nexus/features/minigames/listeners/MatchListener.java#L114-L121) doesn't block it (or really, any inventory events in any minigame) 🤷🏻‍♀️
