### ISSUE TITLE
Improve auto role code

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#511]
**Pugabyte**: The bot occasionally misses joins (server down/plugin reloading), look into improvements such as 
- Diffing last known members
- Discord endpoint for recent joins?

**Comment by lexikiq** [comment]
can confirm discord has no endpoint for recent joins, you'd just have to iterate through the member list and find ones that joined since the bot was last online

fwiw, i have a discord moderation bot that's basically 100% uptime with this feature :P

**Comment by Blast-MC** [comment]
Moved to UB3R for auto-nerding people
