### ISSUE TITLE
Rewriting Litebans

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#528]
- announce to staff the first time someone logs in after being banned
- nameban
- clickable messages everywhere
- support multiple player names in one command
- Include a system to determine suggestions for what punishment's a players could receive, from their history, to what they've done now

**Comment by lexikiq** [comment]
some basic punishment menu (/punish username) which shows the user's history (as a separate page, represented by various colored concrete with item lore showing duration and reason?), watchlist info, and buttons to kick/mute/ban (you'd enter in a duration for the latter two in a sign/anvil gui) would be nice so we can see all information in one place
