### ISSUE TITLE
non-staff are able to transiently see vanished staff members as per picture below

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#534]
Submitted by **Amixalot**

![image](https://cdn.discordapp.com/attachments/813457039505227796/814310964299694131/2021-02-24_20.35.32.png)

**Comment by Pugabyte** [comment]
The image shows a staff member in spectator mode, not vanish. I did however add some code to try to make sure the [V] isnt visible for longer than a couple milliseconds.
