### ISSUE TITLE
Holographic Displays tab complete shows vanished players

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#541]
<img src=https://i.imgur.com/AJOYRqJ.jpg>

Mashyisfat said he could see blast & pug, even tho they are not on tab.

**Comment by Pugabyte** [comment]
CNR 
![image](https://user-images.githubusercontent.com/12417961/116304367-7ec5cc80-a770-11eb-970f-e5630d397573.png)
