### ISSUE TITLE
Siege is broken

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#565]
**lexikiq**:
- The defender's flag/sign doesn't get deleted when grabbed
- The flag dropped on death is "[Minigame] / Flag / Capture / Red" instead of "[Minigame] / Flag / Blue"
- "Xyz returned the flag" is posted in chat every time a defender right clicks their flag, causing spam

**Comment by lexikiq** [comment]
cannot reproduce anymore, maybe fixed somehow? or some weird fluke? 🤷🏻‍♀️
