### ISSUE TITLE
Add higlighting to /alerts matches ingame

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#57]
**Pugabyte**: Make the alerts stand out. I've also considered auto underlining links in the past, should visit that here.

**Comment by Pugabyte** [comment]
I have decided not to do both of these things.

For the highlighting alerts, I don't want to make a word bold to everyone when it only applies to one person.
For the underlining links, I just find underlining too annoying as it blocks off part of the next message.
