### ISSUE TITLE
no perms for /nopickup

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#572]
**lexikiq**: "&cYou do not have permission to do that!", wakka tried to fix it but he says i have perms for nexus and pv so ¯\_(ツ)_/¯

**Comment by WakkaFlocka239** [comment]
the nexus command has permission "pv.use", moderator has it set, operator inherits it.
the command it runs has the permission "pv.toggleitems", moderator has it set, operator inherits it.

"pv.use" is used on `/ni` too, but they have access to this command.

I don't know what's blocking it

**Comment by Pugabyte** [comment]
Just had to delete legacy permission data from lexi's user
