### ISSUE TITLE
Add RGB to /itemname gradient

### ISSUE THREAD

**Issue by lexikiq** [Pugabyte/BearNation#576]
Like in /prefix

This might already be implemented but I couldn't get it to work a few days ago when I tried

**Comment by Pugabyte** [comment]
![image](https://user-images.githubusercontent.com/12417961/113605820-2be77200-9615-11eb-8583-7247eb0688a0.png)

What was happening when you tried?

**Comment by lexikiq** [comment]
ah, didn't realize i was supposed to include ampersands
