### ISSUE TITLE
Delayed Bans doesn't work properly for IP bans

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#586]
**Lexi**: not 100% sure but this is what we believe happened with shlimzigibula and their alt/sockpuppet: IP Ban Player1, delay bans intercepts it and removes it, Player1 never joins to get banned, Player2 joins and is not banned

**Comment by WakkaFlocka239** [comment]
Delayed Bans written a kind of hacky way, any issues like this should be fixed with the rewrite of Litebans
