### ISSUE TITLE
Queued reloads don't check for new invs/minigames

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#592]
**Lexi**: I deployed, the reload was queued due to 3 open SmartInvs, so I started a minigame while we waited. Then a little before it started, Nexus reloaded.

**Comment by Pugabyte** [comment]
Not true. https://github.com/Pugabyte/Nexus/blob/master/src/main/java/me/pugabyte/nexus/features/NexusCommand.java#L192

**Comment by lexikiq** [comment]
oh, because it hadn't started, ok
