### ISSUE TITLE
Crates inconsistently giving incorrect item amounts

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#595]
**Lexi**: No rhyme or reason to it. Sometimes they're doubled (would explain how i had 21+ mystery keys but only 14 logged in bridge), sometimes it was cut in half or in a quarter, some other users reported completely random numbers.

**Comment by lexikiq** [comment]
Looks like PlayerUtils#hasRoomFor can cause the items to duplicate (it gave me the items and then didn't clear them from my inventory). Likely cause for VPS duplication glitch as well.

**Comment by lexikiq** [comment]
Seems fixed by https://github.com/Pugabyte/Nexus/commit/2e1f856adae195a26b663eadb7422c98695ccaa6

**Comment by lexikiq** [comment]
Cause of redstone rewards being wrong was just the title being wrong
