### ISSUE TITLE
Crate item counts are getting messed up

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#597]
**Lexi**: Possibly another pass by reference error, sometimes the actual saved amount in item crates is getting edited to be lower (64 torches became 1, popped chorus fruit became something i forget)

**Comment by lexikiq** [comment]
Fixed by https://github.com/Pugabyte/Nexus/commit/9051bbf1ff7c20c74890930ae0fb2c5ffd29ac05
