### ISSUE TITLE
Player Location List

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#601]
**Josh**: A command like /list but which shows which world players are located in. I know that /whotf can track what world a player is in, so is there a way to check everyone with a single command? Would be useful to quickly check which players are in creative for example.

**Comment by lexikiq** [comment]
Closed by https://github.com/Pugabyte/Nexus/commit/1427795f25f086fdaaa5561ccaec42a1bccd3a15

**Comment by lexikiq** [comment]
Should probably also display their playtime, colored in red if less than an hour
