### ISSUE TITLE
normal players are able to create npcs in the minigame and creative worlds 

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#602]
**Drakimau**: Knack_Knack was messing around putting his own npcs on the podiums in the minigame lobby and spawning them in a creative plot he had building perms in

**Comment by Pugabyte** [comment]
Fixed by https://github.com/Pugabyte/Nexus/commit/5165bd48dbced1caf67be266a6f87a6472d9aadb, but Citizens is randomly not throwing the NPC teleport event. [Reported in discord](https://canary.discord.com/channels/315163488085475337/315625512753954816/831373272142708746)
