### ISSUE TITLE
Workaround remnant hearts in mcMMO deaths

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#609]
**Lexi**: Get the hover text of the mob, parse out the UUID, then find the mob and get its display name or translatable name

![img](https://cdn.discordapp.com/attachments/158998209140752384/832675834674151434/unknown.png)

**Comment by lexikiq** [comment]
also implement a filter for #bridge death messages (replace hearts with "a mob" ig)

**Comment by lexikiq** [comment]
while i'm at it, should escape markdown for bridge death messages
