### ISSUE TITLE
Bleeding damage persists with PVP disabled

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#618]
**Lexi**: mcMMO's bleeding doesn't fire an EntityDamageByEntityEvent. might submit a fix. [relevant source code is here](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/runnables/skills/RuptureTask.java)

**Comment by Pugabyte** [comment]
fwiw 
![image](https://user-images.githubusercontent.com/12417961/115299911-5e24c380-a12d-11eb-8cde-aace992de3de.png)

**Comment by lexikiq** [comment]
Fixed by mcMMO-Dev/mcMMO#4498
