### ISSUE TITLE
Mutes don't apply until chatting

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#626]
**Lexi**: Even if the user is online & not AFK, mutes don't apply until they chat.

![image](https://cdn.discordapp.com/attachments/133947136382468096/836413698419458058/unknown.png)

Bonus: double prefix again

**Comment by Pugabyte** [comment]
Fixed in https://github.com/Pugabyte/Nexus/commit/a29067a7d5247324678189cbbe6cda48d014b2eb
