### ISSUE TITLE
add /delayed unfreeze

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#632]
**Dom**: something similar to delayed ban that would unfreeze players when they log in after their ban expires or similar situations. Also make it usable from Discord

**Comment by Pugabyte** [comment]
You should be able to unfreeze offline players, which I believe is effectively what you want

**Comment by Pugabyte** [comment]
![image](https://user-images.githubusercontent.com/12417961/116427028-a6b93c80-a811-11eb-8932-edb0bd39c75c.png)
