### ISSUE TITLE
Move XRuns and Parkours to minigame plugin and use region checkpoints

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#65]
**Pugabyte**:

**Comment by BearNationSMP** [comment]
**Pugabyte**: Don't put clickable minigame quit signs along the path of XRuns, I've clicked them accidentally a few times trying to click the checkpoint sign

**Comment by BearNationSMP** [comment]
**Pugabyte**: Another XRun in the BA waiting to be added. `/tppos 1046 27 489`

**Comment by BearNationSMP** [comment]
**Pugabyte**: fix death region overrides @Pugabyte

**Comment by Noahkiq** [comment]
all x-runs have had clickable quit signs removed and checkpoint regions added

**Comment by Noahkiq** [comment]
- [ ] icebreaker (convert to mgm plugin)
- [ ] icedungeon (convert to mgm plugin)
- [ ] thecore (convert to mgm plugin)
- [X] wizardtower (add checkpoint regions)
- [ ] compact (convert to mgm plugin (or remove it? as this map is garbage))
- [X] projectsixreset (checkpoint regions, remove clickable quit signs)
- [X] snowwayout (checkpoint regions)
- [ ] setup xrun in BA

**Comment by Noahkiq** [comment]
icebreaker is pretty garbage too actually. (literally a rectangle of ice and snow created with worldedit, also overly difficult.)

icedungeon is also pretty bad. (walls are slightly less shit but still really bad, but course is less infuriating than the other one. still really difficult, but not necessarily a bad thing here as it's not overkill)

wizardtower is... not super difficult, but also very bland. junglerumble also isn't super difficult, and is less visually garbage (and thus probably the best parkour map we have right now). and finally, thecore is okay.

**Comment by JustSteveThings** [comment]
Unsure whats supposed to be done?

**Comment by Noahkiq** [comment]
pug didnt like the old checkpoint system and scrapped it for his own  
/checkpoint edit <map>  
/checkpoint <create|remove> <start|end|#>

**Comment by Noahkiq** [comment]
btw, you can remove the old checkpoint regions using
```
/mgm edit
select Regions & Nodes
right click on the regions named "CheckpointX" to delete (iirc. might be shift + right click or similar)
save minigame
```
