### ISSUE TITLE
mcMMO level resets for rewards

### ISSUE THREAD

**Issue by Pugabyte** [Pugabyte/BearNation#7]
mcMMO is a great plugin for helping keep people interested by having reachable goals and benefits of progressing. However, there is a cap on the levels and once someone reaches the cap, they may lose motivation to continue playing. 

This idea is fairly simple; create a menu that will allow you to reset your mcMMO level for a specific skill in exchange for a reward. The reward can be related to the skill or completely random. 

----
Steps needed to complete:

- [x] Discuss circumstances in which they can reset their levels (can they reset at 50? only 100?)
- [x] Design the menu
- [x] Come up with ideas for rewards
- [ ] Program the menu

**Comment by PugaBear** [comment]
@WarriorTark @TheEpicScrub Can you two please come up with rewards for resetting your mcMMO levels? We need at least one reward for each of the following skills:
```
All at the same time
Swords
Mining
Excavation
Axes
Herbalism
Fishing
Acrobatics
Repair
Archery
Taming
Woodcutting
Unarmed
Alchemy
```

If you would like to do different rewards for how many times you reset (e.g. get a better reward on the third reset, and on the fifth), I'm good with that, but it's not required. You decide

Like I said in the first comment, we have generally imagined these rewards will be related to the skill itself- for example, resetting your fishing skill can get you some pufferfish, and a lure book, or something. 

Keep in mind that (some of) these skills are *extremely* hard to complete. The rewards should be pretty great. Feel free to give me or Filid examples for feedback.

**Comment by FilidDamhsoir** [comment]
Discuss circumstances in which they can reset their levels (can they reset at 50? only 100?)
thoughts?
Filid - Today at 12:50 AM
I'd say only at 100.

i had an idea- we could leave 100 the max for bonuses from level- but move the cap to 200, at 100 or above they can reset.  Maybe with reward  tiers depending on if they give up 100, 150, 200 levels? (or any set of tiers yall think is fair- 100, 125 150 ect)

**Comment by WarriorTark** [comment]
https://docs.google.com/document/d/1vsafiboK-iPIxYHFivJ6CGe9dS15mK7VlQSK3aVckZU/edit?usp=sharing

**Comment by FilidDamhsoir** [comment]
https://docs.google.com/document/d/1ZoX3rO0d7NRZ4y_57KBY8E4g8D40ijntIp0loijqy7c/edit?usp=sharing

**Comment by FilidDamhsoir** [comment]
We were also considering every time x number of resets happen, the level cap server wide increased by 10. They can still reset at 100 (or higher) but it pushes the total cap
