### ISSUE TITLE
Minigame chat channels

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#70]
**Pugabyte**: Hook into the Minigames plugin and send players clickable messages to allow them to switch to their team chat channel.

**Comment by Pugabyte** [comment]
https://github.com/AddstarMC/Minigames/tree/master/Minigames/src/main/java/au/com/mineauz/minigames/events

**Comment by Pugabyte** [comment]
Games to watch for:
Paintball
CTF
1F-CTF
4TDM
TDM
Walls

Teams:
Red
Blue
Green
Yellow

**Comment by Pugabyte** [comment]
Need to fix an issue regarding the end of game messages
