### ISSUE TITLE
Make sure all the games noted in #70 have a gametype set

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#75]
Make sure the gametype is _exactly_ what is in the comment on #70

**Comment by Noahkiq** [comment]
- [ ] Paintball
- [ ] Capture The Flag
- [ ] One Flag Capture The Flag
- [ ] Four Team Death Match
- [ ] Team Death Match
- [ ] The Walls

**Comment by Noahkiq** [comment]
if case-sensitivity matters, CTFs are `Capture the Flag` and `One Flag Capture the Flag` respectively
