### ISSUE TITLE
More daily rewards

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#83]
**Pugabyte**: We originally started with 30 days and planned to see how people liked it. It's been a *huge* success. At the time of writing this, there are 3 people with streaks over 30 days, and there have been about 5 more people in the past, so it's time we expanded the rewards. 

Up for grabs

**Comment by Noahkiq** [comment]
login rewards google doc is linked in #staff-think-tank :eyes:

**Comment by RavenOnACloud** [comment]
https://docs.google.com/spreadsheets/d/1FVUM2zN91XYvv_PxBJzzV4JuNO8wzbphhmDkKOXPrpM/edit#gid=0

Extended it by 30 days
