### ISSUE TITLE
Future server-wide voting goal rewards

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#85]
**Pugabyte**: Access to a donation perk

**Comment by Pugabyte** [comment]
Ideas from meeting form:

- Entire month/longer access to donation perks creates more of a reliance on the perk
- Eco only daily rewards (not streak based)
- Increased drop rate on mob heads
- Cheaper entry to the wither arena
- Let players pick an event out of a list
- Enchantments
- Rare items
- KillerMoney boost
- mcMMO boost
- Exp boost

**Comment by BearNationSMP** [comment]
**Pugabyte**: server store sale
