### ISSUE TITLE
Minigame VPS ideas

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#86]
**lexikiq**: 
- custom hats
- custom death effects: lightning, tnt, custom sound, skeleton/zombie npc [none would do damage, npc's wouldn't move and would only last a few seconds]
- particle effects (see if we can find a working plugin? but i'd imagine it'd be easier to code a custom one that only works while in certain MGM gamemodes + with certain permissions)

**Comment by BearNationSMP** [comment]
**Noahkiq**: | suggestions:
- add Hat Points currency which you can buy with vote points (and maybe real money..?)
- hats would be worth a few hat points, cooler/rarer hats would be worth more
- occasionally drop crates after winning a map that supports cosmetics. (shouldn't be *too* rare) -- MGM plugin has rewards, and i believe it makes the player run the command which we can use for detecting if they should win a crate or not
- more rarely drop actual hats, or some other cosmetics. more expensive cosmetics = rarer
- add keys that can be purchased with Hat Points which unlock crates, which gives the player a random hat. (again, slightly prefer more common hats)
- add special hats that have enchantment glow and can only be obtained from crates
- also, maybe make non-hat items crate-exclusives? like death or particle effects. add em to a select few crates and make em fairly rare. (probably more or as rare as enchanted hats)
- also, crates should have lore on them that lists what items you can get. (probably color coded to show how common they are)
props to auto/noah who gave me some ideas. (great ~~minds~~ names think alike)

**Comment by BearNationSMP** [comment]
**Noahkiq**: side notes i think i forgot to mention: hats will still be purshasable using Hat Points, but players can also buy crates or keys if they'd like. keys should also be the one thing you can only get from the Hat Point store (and not from random drops/a crate)

**Comment by BearNationSMP** [comment]
**Noahkiq**: sukhy's subconcious just created a great idea: lobby gadgets, like on mineplex. few good things i can think of would be particle effects, fire trail boots, and fireworks. we'd need a custom plugin to handle that stuff tho.
also, since we (iirc) have a plugin to give players permissions in certain worldguard regions, why not allow players to ride pets they've bought at the enjin shop?

**Comment by Noahkiq** [comment]
summary/suggestions from staff meeting feedback form (pls comment if i missed something or you'd like to provide more feedback):
- Lobby items (fireworks, trails, `/ce menu` items)
- Get HP after winning game (amount changing depending on gamemode, also random factor)
- Add Minigame Achievements which reward you with Hat Points or rare cosmetics
- Custom Death Messages
- Victory Dances
- Option to replace a monthly voting reward with some item here (ie rare hat, special crate, etc)
- Let all players have a (same) random chance of getting a crate after a round ends. Don't award crates based on skill level.
- Custom full-gear armor sets in gamelobby
- Add option for staff to temporarily disable lobby items (for screenshots)
- Make sure death effects don't cause lag
- Don't touch armor that's used to identify teai thinms
- No hat points?
- Particle effects should be limited to certain situations (ie in CTF games, if the person has the flag) -- Allowing particle effects all the time can easily be distracting and cause lag
- Bow trails
- Allow purchasing items through donations if popular

**Comment by Pugabyte** [comment]
initial lobby stuff:
- tnt
- push
- snowball launcher
- particles
- armour/hats
