### ISSUE TITLE
Proper Juggernaut

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#89]
**Noahkiq**: kinda possible now using infected %s but would only work for a certain # of people... on the plus side(?), that would allow us to balance it more... but then we have thetournament dilemna where nobody would play it. if we could get the max player per team count working, we could try doing some balancing using minigame regions , conditions, and multiple loadouts that we can forcefully reequip

**Comment by JustSteveThings** [comment]
110% possible there is a beta test set to the live map marscamp will need 10 people + to test

**Comment by JustSteveThings** [comment]
Done
