### ISSUE TITLE
Re-implement recruiting

### ISSUE THREAD

**Issue by Pugabyte** [Pugabyte/BearNation#9]
One of the early features of Bear Nation allowed someone to be rewarded for inviting others to the server. There were constraints, such as:
- The recruiter needs to have Member+ rank
- The recruitee needs to have Member rank 
- More can be added if we feel it is necessary

----

- [ ] Design UI
- [x] Decide on reward(s) (previously was vote points)
- [x] Decide on constraints
- [ ] Program it

**Comment by BearNationSMP** [comment]
**PugaBear**: 20 vote points as reward. Make sure to add checks for when the players joined
