### ISSUE TITLE
Animal teleportation pens

### ISSUE THREAD

**Issue by Pugabyte** [Pugabyte/BearNation#94]
Suggestion originally from odyssey2012 in #bugs-support-and-suggestions

I got the general feel that people weren't entirely on board with the idea of selling animals from signs, and that seems like a large undertaking code-wise, so we're gonna pass on that.

However, everyone liked the idea of being able to teleport animals somehow.

- Much like the original Guest/Member animal portals, allow players to teleport animals from warp to warp. 
- Fee for use
    - Based on how many/what type of animals they are teleporting
- For a much larger fee, allow them to be teleported directly to you.
- Only for Member+ and above?

**Comment by Pugabyte** [comment]
- Player moves into teleport region (located in warp), and runs `/atp` 
- Automatically detect all animals in the region and calculates price
    - Chickens, Wolves & Cats: 50
    - Pigs & Rabbits: 100
    - Cows, Sheep & Polar Bears: 150
    - Horses & Llamas: 250
    - Villagers: 500

- Bring up a GUI with 
    - Each of the survival warps
    - An item that brings up a sign menu, where they can type a home name (their home only) (10x price)
        ```
        [blank for input]
        ^^^^^^^^^^^^^^^^ 
        Input home name
        to teleport to
        ```
- Show them the final cost and have them confirm it to begin teleportation

**Comment by Pugabyte** [comment]
Code complete. Need pens at each warp for teleportation. 
- [ ] Need to have a region named `atp_<warp name>` around them
- [ ] Need to have an ATP warp needs to be set in the middle (`/atp warps set <warp name>`)

Warp names follow this standard:
- west
- northwest
- west2
- northwest2
- spawn

**Comment by GoddessOfNyx** [comment]
Hey Griffin, each time you teleport, it increments the cost. It is not changing the price depending on how many animals you have to teleport, but if you've done it before.

**Comment by JustSteveThings** [comment]
All but northwest southwest and south 2 are done didn't have time

**Comment by WakkaFlocka239** [comment]
You actually have quite a few more than that, the ones in crossed in red are done, the ones boxed in green need to be built.
![warpstodo](https://user-images.githubusercontent.com/9204295/40943214-e52a76c6-6815-11e8-96ba-f82dfb2e6817.png)
